version: '3'

services:
  app:
    container_name: spring
    image: openjdk:11-jdk
    environment:
      TZ: "Asia/Seoul"
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - java -jar ./build/libs/*.jar
    restart: always

  promtail:
    container_name: promtail
    image: grafana/promtail
    environment:
      TZ: "Asia/Seoul"
    ports:
      - 1514:1514
    volumes:
      - ./logs:/var/log
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/config.yml
#    command: -config.file=/etc/promtail/promtail-config.yml