version: '3'

services:
  app:
    container_name: spring
    image: openjdk:11-jdk
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - .:/app
    entrypoint: [ "/bin/bash", "-c" ]
    command:
      - java -jar ./build/libs/*.jar
    restart: always

  nginx:
    depends_on:
      - app
    container_name: nginx
    image: geneaky/nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always

  promtail:
    image: grafana/promtail
    depends_on:
      - nginx
    container_name: promtail
    volumes:
      - ./logs:/var/log
      - ./monitoring/promtail:/mnt/config
    command: -config.file=/mnt/config/promtail-config.yml