global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['172.31.41.87:8080']
  #      - targets: ['host.docker.internal:8080']

  - job_name: 'rabbitmq-prometheus'
    static_configs:
      - targets: ['172.31.36.181:15692']