### stomp connection start
WEBSOCKET ws://localhost:8080/stomp-connection
Authorization: {{jwt_token}}

CONNECT
accept-version:1.2

^@


### message
SEND
DESTINATION: /pub/chat.enter.111

hello queue
^@