### 서재에 책 등록
POST localhost:8080/v1/api/bookshelves
Authorization: {{jwt_token}}
Content-Type: application/json

{
  "bookRequest": {
    "isbn": "1156640199 9791156640196",
    "title": "디자인 시스템 실무 with 피그마",
    "authors": [
      "이영주"
    ],
    "publisher": "한빛아카데미",
    "publishAt": "2024-02-09",
    "bookCoverImageUrl": "https://search1.kakaocdn.net/thumb/R120x174.q85/?fname=http%3A%2F%2Ft1.daumcdn.net%2Flbook%2Fimage%2F6558820%3Ftimestamp%3D20241001160358"
  },
  "readingStatus": "READING",
  "star": null
}

### 서재에서 책 조회
GET localhost:8080/v1/api/bookshelves?readingStatus=READING&size=3&page=0&sort=updatedAt,DESC
Authorization: {{jwt_token}}

> {%
  client.test("Request executed successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.global.set("bookShelfId", response.body.contents[2].bookShelfId);
  client.global.set("isbn", response.body.contents[2].isbn);
  client.global.set("publishAt", response.body.contents[2].publishAt);
%}

### 서재에서 책 삭제
DELETE localhost:8080/v1/api/bookshelves/{{bookShelfId}}
Authorization: {{jwt_token}}

### 서재 페이지|별점|독서상태변경
PUT localhost:8080/v1/api/bookshelves/{{bookShelfId}}
Authorization: {{jwt_token}}
Content-Type: application/json

{
  "pages": 100,
  "star": "FIVE",
  "readingStatus": "READING"
}

### 서재에 등록된 책이면 조회
GET localhost:8080/v1/api/bookshelves/book?isbn={{isbn}}&publishAt={{publishAt}}
Authorization: {{jwt_token}}