name: bookchat-service-test

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  TEST:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
          - 3306:3306
      rabbitmq:
        image: rabbitmq
        ports:
          - 61613:61613
          - 15692:15692
          - 5672:5672
        options: --name rabbitmq
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
    permissions:
      checks: write
      pull-requests: write
      actions: read

    steps:
    - name: enable rabbitmq stomp plugin
      run: docker exec rabbitmq rabbitmq-plugins enable rabbitmq_stomp rabbitmq_web_stomp

    - name: Check out
      uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '11'
        
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew
      shell: bash

    - name: Test with Gradle
      run: ./gradlew clean test -x asciidoctor
      shell: bash

    - name: Test Report
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: '**/build/test-results/test/TEST-*.xml'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Add coverage to PR
      uses: Madrapps/jacoco-report@v1.3
      with:
        paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        min-coverage-overall: 0
        min-coverage-changed-files: 0
